# Generated by Django 5.2.1 on 2025-05-22 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fields',
            name='profile_pic',
        ),
        migrations.AddField(
            model_name='fields',
            name='profile_pics',
            field=models.ImageField(blank=True, default='profile_pics/default.jpg', null=True, upload_to='profile_pics/'),
        ),
    ]
