# Generated by Django 5.2.1 on 2025-05-22 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0002_remove_fields_profile_pic_fields_profile_pics'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fields',
            old_name='profile_pics',
            new_name='profile_pic',
        ),
    ]
